services:
  
  collabora:
    image: collabora/code:24.04.13.3.1
    container_name: collabora
    networks:
      - office_net
    cap_add:
      - MKNOD
    environment:
      - username=${COLLABORA_USERNAME}
      - password=${COLLABORA_PASSWORD}
      - dictionaries=en_US,ru
      - domain=collabora\\.exemple\\.com|mycloud\\.exemple\\.com
      - extra_params=--o:ssl.enable=false --o:ssl.termination=true --o:logging.level=trace
    ports:
      - "9980:9980"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9980/hosting/discovery"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s


networks:
  office_net:
    external: true
